"""Generate web_assets.h from index.html + bg.webp + crop.webp.

index.html is gzipped (served with Content-Encoding: gzip); the images are
embedded as-is. Output goes to the project root (next to the .ino) and is
mirrored into firmware/ for Arduino IDE builds.

Runs standalone (python scripts/gen_web_assets.py) or as a PlatformIO
pre-script via prepare_web.py.
"""
import gzip
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 20):
        lines.append(", ".join(str(b) for b in data[i:i + 20]))
    body = ",\n  ".join(lines)
    return (f"const uint8_t {name}[] PROGMEM = {{\n  {body}\n}};\n"
            f"const size_t {name}_len = {len(data)};\n")


def generate() -> Path:
    html = (ROOT / "index.html").read_bytes()
    gz = gzip.compress(html, 9)
    out = ["// Auto-generated by scripts/gen_web_assets.py — do not edit.",
           "#pragma once", "#include <pgmspace.h>", ""]
    out.append(c_array("INDEX_GZ", gz))
    out.append(c_array("BG_WEBP", (ROOT / "bg.webp").read_bytes()))
    out.append(c_array("CROP_WEBP", (ROOT / "crop.webp").read_bytes()))
    header = "\n".join(out).encode()
    target = ROOT / "web_assets.h"
    for dest in (target, ROOT / "firmware" / "web_assets.h"):
        if dest.exists() and dest.read_bytes() == header:
            continue
        with open(str(dest), "wb") as f:
            f.write(header)
    print(f"web_assets.h: index {len(html)} -> {len(gz)} gz, "
          f"total header {len(header)} bytes")
    return target


if __name__ == "__main__":
    generate()
